- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .editorconfig
- README.md
- requirements.txt
- Adds vscode dev container configuration + .editorconfig + open in vscode button for remote containers / clone
- Pin markupsafe to 2.0.1
> chore: add vscode dev container config

- requirements.txt
Pin Jinja2 dependecy `markupsafe` to 2.0.1
> chore: Revert Jinja2 3.* update

- tox.ini
* chore: Update deprecated tox configuration option. See https://tox.wiki/en/latest/config.html#conf-allowlist_externals
* chore: Update tox configuration file format
> chore: Update deprecated tox configuration option

- .github/workflows/checks.yml
- tox.ini
PyPDF2 2.17.* versions have introduced breaking changes for PDF tests.
> test: Pin PyPDF2 to 2.16.* versions

- tests/input/draft-v3-features.xml
- tests/valid/draft-v3-features.prepped.xml
- tests/valid/draft-v3-features.text
- tests/valid/draft-v3-features.v3.py36.html
- tests/valid/draft-v3-features.v3.py37.html
- tests/valid/draft-v3-features.v3.py38.html
- tests/valid/elements.bom.text
- tests/valid/elements.pages.text
- tests/valid/elements.text
- tests/valid/elements.v3.py36.html
- tests/valid/elements.v3.py37.html
- tests/valid/elements.v3.py38.html
- tests/valid/elements.wip.text
- xml2rfc/util/name.py
> fix: Don't attempt to select initials when fullname contains non Latin characters

- tests/input/elements.xml
- tests/valid/draft-v3-features.text
- tests/valid/elements.bom.text
- tests/valid/elements.pages.text
- tests/valid/elements.prepped.xml
- tests/valid/elements.text
- tests/valid/elements.v3.py36.html
- tests/valid/elements.v3.py37.html
- tests/valid/elements.v3.py38.html
- tests/valid/elements.wip.text
- xml2rfc/writers/text.py
Display ASCII names for authors in references with non-Latin characters in
their names.
Fixes #768
> fix: Display ASCII names for authors in references 

- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.py37.html
- tests/valid/manpage.txt
- tests/valid/rfc6787.exp.xml
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.py37.html
- xml2rfc/run.py
- xml2rfc/writers/base.py
- xml2rfc/writers/doc.py
- xml2rfc/writers/expanded_xml.py
- xml2rfc/writers/html.py
- xml2rfc/writers/legacy_html.py
- xml2rfc/writers/nroff.py
- xml2rfc/writers/paginated_txt.py
- xml2rfc/writers/pdf.py
- xml2rfc/writers/preptool.py
- xml2rfc/writers/raw_txt.py
- xml2rfc/writers/text.py
- xml2rfc/writers/unprep.py
- xml2rfc/writers/v2v3.py
Replaces calls to `datetime.date.today()` with the value `None` in various class `__init__()` method signatures and in the default options dictionary. At instance init time, translates `None` into the `today()` call. In `run.py`, simplifies the date argument parsing and is more explicit about calling `today()` when the argument is omitted.
Tests are updated to pass on my system (only running against python 3.7)
Fixes #773. Probably related to https://github.com/ietf-tools/datatracker/issues/3944
> fix: evaluate date.today() on class init, not import

- xml2rfc/templates/doc.xml
- xml2rfc/writers/text.py
[fix: Fix FutureWarning in xml2rfc/writers/text.py](https://github.com/ietf-tools/xml2rfc/commit/b5076cca1ef55727b1b9e78eb90c829a5daf971d)
[fix: Remove rfc2629-xhtml.ent from doc template](https://github.com/ietf-tools/xml2rfc/commit/3431178305723b1fdbbbc80538d152e1e2976d2c)
> fix: Fix warnings in text and manpage

- tests/input/indexes.xml
- tests/valid/docfile.py36.html
- tests/valid/docfile.py37.html
- tests/valid/docfile.py38.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.py36.html
- tests/valid/indexes.v3.py37.html
- tests/valid/indexes.v3.py38.html
- tests/valid/manpage.txt
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.py36.html
- tests/valid/sourcecode.v3.py37.html
- tests/valid/sourcecode.v3.py38.html
- xml2rfc/writers/preptool.py
(with pseudocode, please fill in with proper Python incantations)
> fix: Implement emboldening primary iref entries

- tests/valid/docfile.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/data/xml2rfc.css
Fixes #787
This change removes `display: table` property from `alignCenter` class.
This seems to be a hack to make PrinceXML happy, WeasyPrint doesn't play nicely with the table, hence the cut-off issue.
`alignLeft` and `alignRight` classes doesn't have `display: table` property set.
> fix: Display long ASCII art correctly in PDF

- tests/valid/docfile.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/parser.py
#799 was incomplete, this change fixes the issue.
Fixes #792
>  fix: Use bib.ietf.org for citations 

- Dockerfile
- configtest.py
- test.py
- tox.ini
- xml2rfc/__init__.py
- xml2rfc/run.py
- xml2rfc/writers/pdf.py
* Update weasyprint to 55.0.
* Replace PyPDF2 with pdfplumber.
This changes PDF generation from cairo to pydyf.
Fixes #696
> feat: Update weasyprint to 55.0 

- docker/base.Dockerfile
- docker/dev.Dockerfile
As per comments in https://github.com/ietf-tools/xml2rfc/pull/849#issuecomment-1210075932, attempt to optimize the docker images generated by xml2rfc.
> build: Optimize docker images

- docker/dev.Dockerfile
Otherwise git won't work in the dev image.
I considered a tweak to .bashrc instead; but this seems fine.
> Mark the xml2rfc directory as safe

- xml2rfc/data/xml2rfc.css
> fix: Fix odd page break inside rows in PDF output

- test.py
- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template-old.exp.xml
- tests/valid/draft-template-old.prepped.xml
- tests/valid/draft-template-old.v2v3.xml
- tests/valid/draft-template.exp.xml
- tests/valid/draft-template.html
- tests/valid/draft-template.prepped.xml
- tests/valid/elements.bom.text
- tests/valid/elements.pages.text
- tests/valid/elements.prepped.xml
- tests/valid/elements.text
- tests/valid/elements.v3.html
- tests/valid/elements.wip.text
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.exp.xml
- tests/valid/rfc7911.html
- tests/valid/rfc7911.prepped.xml
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/pdf.py
>  fix: RTL unicode issue in PDF

- tests/input/elements.xml
- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/elements.bom.text
- tests/valid/elements.pages.text
- tests/valid/elements.prepped.xml
- tests/valid/elements.text
- tests/valid/elements.v3.html
- tests/valid/elements.wip.text
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/text.py
Fix for table colspan issue in #833
>  fix: Fix table colspan issue in text format 

- tests/valid/docfile.html
- xml2rfc/writers/html.py
In HTML & PDF outputs, add the published date when `ipr` attribute is not set or set to none.
Fixes #893
> fix: Include the published date when ipr is none

- test.py
- xml2rfc/writers/pdf.py
Use Noto fonts when Roboto Mono font can not display monospaced Unicode characters.
Fixes #906
> fix: Use noto fonts for non-latin unicode monospaced characters

- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/data/xml2rfc.css
- xml2rfc/writers/pdf.py
Ref: https://github.com/ietf-tools/xml2rfc/pull/909#discussion_r992999543
> fix: Remove redundant code labels from CSS

- requirements.txt
- xml2rfc/util/unicode.py
This is supplementary to https://github.com/ietf-tools/xml2rfc/pull/913, which dropped the dependency on kitchen. Here we add a dependency on wcwidth, which is an maintained library to determine the monospace textual length of a string.
> Use wcwidth to determine the monospace textual length of a string

- xml2rfc/writers/pdf.py
This Noto Sans Symbols 2 font provides a "circle" symbol for nested ul > li elements.
Fixes #925
> fix: Add Noto Sans Symbols 2 font to PDF template

- xml2rfc/data/xml2rfc.css
- xml2rfc/writers/html.py
The HTML elements created for a `<sourcecode>` element have class
attributes attached to the `<pre>` element.  In comparison, `<artwork>`
is rendered with class attritributes attached to the outer `<div>`.
Having the classes on the outer `<div>` makes it a LOT easier to style
these properly, so I've moved them in this CL.
> Move sourcecode classes

- xml2rfc/walkpdf.py
> test: Update walkpdf to fix PyPDF deprecation warnings

- .github/workflows/checks.yml
- tox.ini
Weasyprint 57.0 introduced a bug that breaks xml2rfc tests. This is fixed in Weasyprint 57.1.
See https://github.com/Kozea/WeasyPrint/issues/1752
> chore: Skip Weasyprint 57.0 in tests

- docker/base.Dockerfile
> fix: Update to pypdf>=3.2.1 on base docker file

- xml2rfc/data/xml2rfc.css
See https://github.com/ietf-tools/datatracker/pull/5071 for more context.
This removes the blue coloration from internal links that immediately follow an `<iref>` tag (rendered as a `span.iref`).  This reduces visual noise arising from the use of keyword linking.  See https://github.com/cabo/kramdown-rfc/wiki/Syntax2#index-entries for details on how that operates.
> feat: Lighter styling on internal iref links

- xml2rfc/data/xml2rfc.css
This change removes the `width: extend-to-zoom` setting from `@viewport`.
Fixes #974
> fix: Remove extend-to-zoom from viewport in CSS

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/parser.py
> fix: Remove old tools server from BibXML lookup locations

- requirements.txt
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc6787.html
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/run.py
Platformdirs is API compatible with appdirs, all that needs to be changed is the module name.  It is a friendly fork of appdirs that was created after appdirs went unmaintained in 2020.
I've tried this out at tests all still pass.  I think it's a straightforward change and it's better to use something that's got active maintainers.
> fix: Switch from appdirs to platformdirs, since it is maintained

- xml2rfc/parser.py
`XInclude` should be used instead of ENTITY references and XML Processing Instructions (PIs) that allow external inclusions [1].
This change adds a warning when include PIs (`<?rfc include='<reference>' ?>`) are used with xml2rfc v3.
Fixes #1006
[1] https://datatracker.ietf.org/doc/html/rfc7991#appendix-B.1
> fix: Warn when reference uses PIs

- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/preptool.py
The `writers.preptool.slugify_name()` helper kept a set of `seen_slugs` as a module-level variable. As a result, uniqueness among slugs was enforced for the entire lifetime of a module import, including across `PrepToolWriter` instances and across multiple calls to `prep()`.
In xml2rfc itself, this appears to have been adding unnecessary "-2" suffixes on many HTML ids, at least in the tests. For datatracker's use of xml2rfc as a library, this was causing difficulties with long-lived celery workers by adding suffixes to prevent collisions between entirely separate drafts and eventually running out of unique slugs.
This makes the `slugify_name()` procedure a method on `PrepToolWriter` and resets the `seen_slugs` cache, now a property of the instance, on each invocation of `prep()`
> fix: Reset seen_slugs cache on every prep run

- tests/input/draft-template.xml
- tests/valid/draft-template.exp.xml
- tests/valid/draft-template.html
- tests/valid/draft-template.pages.text
- tests/valid/draft-template.prepped.xml
- tests/valid/draft-template.text
- tests/valid/draft-template.txt
- tests/valid/draft-template.v2v3.xml
- tests/valid/draft-template.v3.html
- xml2rfc/parser.py
This change adds a `.xml` extension when the `.xml` extension is missing in BibXML reference requests.
Fixes #1003
> fix: Add xml extension to BibXML requests

- xml2rfc/writers/pdf.py
Previously, the table of contents only included the section numbers and a link into the document.  Neither is really helpful when navigating a printout.
Add page numbers to the table of contents in the generated PDF.
> Include page numbers in the TOC when generating PDF.

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/elements.bom.text
- tests/valid/elements.pages.text
- tests/valid/elements.prepped.xml
- tests/valid/elements.text
- tests/valid/elements.v3.html
- tests/valid/elements.wip.text
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/util/unicode.py
- xml2rfc/writers/base.py
- xml2rfc/writers/preptool.py
- xml2rfc/writers/v2v3.py
This PR that does the following:
* Remove guards for non-ASCII & non-Latin characters.
* Removes automatic downcoding of non-ASCII characters.
* Allows Unicode characters in all elements.
* With the `--warn-bare-unicode` command line option, `xml2rfc` will warn if Unicode characters are present in any element that traditionally Unicode content is not allowed.
Traditionally, Unicode content is allowed in the following elements: `artwork`, `city`, `city`, `cityarea`, `cityarea`, `code`, `code`, `country`, `country`, `email`, `email`, `extaddr`, `extaddr`, `organization`, `organization`, `p`.
With #895 bare use of Unicode characters is added to the `t` element. But it's implemented in such a way that `--warn-bare-unicode` warns about it. This PR will keep that warning.
Fixes #960.
> feat: Allow Unicode characters everywhere 

- Makefile
- tests/input/elements.xml
- tests/input/rfc7911.xml
- tests/valid/docfile.html
- tests/valid/elements.prepped.xml
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.exp.xml
- tests/valid/rfc7911.prepped.xml
- tests/valid/rfc7911.v2v3.xml
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/run.py
Fixes #1013
This fix prevents `xml2rfc` from running v2v3 conversion and preptool stages on prepped documents.
Prepped documents are identified by the `prepTime` attribute in the `rfc` element.
This fix gains a considerable performance gain.
```
root@8bc787553164:~/xml2rfc# time xml2rfc --html --text --pdf rfc9427.xml
Created file rfc9427.txt
Created file rfc9427.html
Created file rfc9427.pdf
real	2m16.207s
user	2m14.799s
sys	0m0.572s
root@8bc787553164:~/xml2rfc# time xml2rfc --html --text --pdf rfc9427.notprepped.xml
Created file rfc9427.notprepped.txt
Created file rfc9427.notprepped.html
Created file rfc9427.notprepped.pdf
real	0m3.785s
user	0m2.611s
sys	0m0.337s
```
```
root@8bc787553164:~/xml2rfc# time xml2rfc --html --text --pdf rfc9427.xml
Created file rfc9427.txt
Created file …
```
> fix: Avoid running v2v3 conversion and preptool on prepped documents

- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/data/xml2rfc.css
When a word is too big to fit in a line in HTML and PDF outputs, break the word.
Fixes #687
> fix: Break word when line overflows

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/draft-v3-features.text
- tests/valid/elements.bom.text
- tests/valid/elements.pages.text
- tests/valid/elements.text
- tests/valid/elements.wip.text
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/text.py
This change preserves `&nbsp;` in `dd` elements in the text output.
Fixes #1022
> fix(text): Preserve NBSP in dd

- tests/valid/draft-miek-test.html
- tests/valid/draft-miek-test.prepped.xml
- tests/valid/draft-miek-test.v2v3.xml
- tests/valid/draft-miek-test.v3.html
- tests/valid/draft-template-old.prepped.xml
- tests/valid/draft-template-old.v2v3.xml
- tests/valid/draft-template.html
- tests/valid/draft-template.prepped.xml
- tests/valid/draft-template.v2v3.xml
- tests/valid/draft-template.v3.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/rfc7911.prepped.xml
- tests/valid/rfc7911.v2v3.xml
- tests/valid/rfc7911.v3.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/v2v3.py
This change preserves `<t>` elements inside `<ol>` and `<li>` elements
on v2v3 conversion.
Fixes #850
> fix(v2v3): Preserve t element in ol and li 

- .github/workflows/checks.yml
- docker/base.Dockerfile
- setup.cfg
- tox.ini
- xml2rfc/run.py
WeasyPrint==60.0 is breaking tests for some Python versions.
Until we figure out the issues restrict WeasyPrint==60.0.
> chore: Restrict WeasyPrint version 60.0

- tests/input/elements.xml
- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/elements.bom.text
- tests/valid/elements.pages.text
- tests/valid/elements.prepped.xml
- tests/valid/elements.text
- tests/valid/elements.v3.html
- tests/valid/elements.wip.text
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/html.py
This change fixes a bug where child elements were not rendered in the `xref` element with a `section` attribute.
This change only affects HTML & PDF outputs.
Fixes #1034
Example XML snippet:
```
<section anchor="introduction"><name>Introduction</name>
<t>See Section <xref target="RFC8610" section="2" sectionFormat="bare">The <em>Style</em> of Data Structure Specification</xref> of <xref target="RFC8610">CDDL</xref>.</t>
<t>See <xref target="RFC8610" section="2" sectionFormat="parens">The <em>Style</em> of Data Structure Specification</xref> of <xref target="RFC8610">CDDL</xref>.</t>
<t>See <xref target="RFC8610" section="2" sectionFormat="comma">The <em>Style</em> of Data Structure Specification</xref> of <xref target="RFC8610">CDDL</xref>.</t>
<t>See <xref target="RFC8610" section="2" …
```
> fix: Render child elements in the xref element

- .github/workflows/checks.yml
- docker/base.Dockerfile
- setup.cfg
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- tox.ini
- xml2rfc/run.py
WeasyPrint 60.1 has fixed the crash caused by the wrong UTF-8 indices.
Allow installing v60.1 and above while avoiding v60.0.
> chore: Allow WeasyPrint v60.1

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/preptool.py
This PR addresses two issues:
* Duplicate entries per term in the index.
* Duplicate terms in the index.
Fixes #988
> fix: Deduplicate index entries

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/pdf.py
Set `presentational_hints` option in WeasyPrint so that HTML
presentational hints are respected.
See https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#supported-html-tags
Fixes #1054
> fix: Follow HTML presentational hints in PDF

- xml2rfc/data/xml2rfc.css
This reverts: "feat: Lighter styling on internal iref links (#963)" See https://mailarchive.ietf.org/arch/msg/rsab/F9QOvdVX2amsX1bgR4DGVTzQat8/
This reverts commit dbdda51a16083da0762355ebe0902c3bc2a78a39.
Fixes #1058
> revert: Lighter styling on internal iref links

- requirements.txt
- setup.cfg
`file: requirements.txt` is only supported by setuptools>=62.6.
Fixes #1049
> chore: List required dependencies

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/draft-v3-features.v3.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/html.py
* This change removes emphasis on xref content in headings.
* This change also adds `xref` content to `name` when the `format="none"` in the `xref` element.
* When `xref` is in `title`, if `xref` has a target to a `reference` use
square brackets (`[ <target text> ]`).
* If the `xref` target is not a reference don't use brackets or parenthesis.
* If the `xref` element has text content:
For `reference` targets:
`<text content> [<target>]`
For other targets:
`<text content> (<target>)`
Fixes #683
> fix: Remove emphasis from xref in headings and fix xrefs in headings 

- .github/workflows/pypi-publish.yml
Fixes #1041 
Both PyPI and test PyPI has been configured as following:
```
Publisher information:
Publisher name: GitHub
Workflow: pypi-publish.yml
Owner: ietf-tools
Repository: xml2rfc
Environment: release
```
Release GitHub environment has two protection rules:
* Workflow can only be run by member of `ietf-tools/dev`.
* Branch limited to `main`.
> ci: Use PyPI trusted publishing

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/__init__.py
Use `importlib.metadata` instead of `pkg_resources` from `setuptools` since `pkg_resources` is deprecated.
Fixes #1072
> fix: Use importlib.metadata

- xml2rfc/__init__.py
This improves #1079 because some environments separate versions and library names differently.
> fix: Improve xml2rfc version information logic

- xml2rfc/__init__.py
> fix: Silently pass when weasyprint is not installed

- xml2rfc/writers/preptool.py
PR #1017 allowed Unicord characters everywhere.
This fixes a bug that xml2rfc was guarding against non-ASCII characters in attribute values.
With `--warn-bare-unicode`, xml2rfc will warn if non-ASCII characters are present in attribute values.
Fixes #1105
> fix: Allow non-ASCII values in all attributes

- test.py
- xml2rfc/writers/text.py
> fix(text): Don't break URLs in annotation

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/draft-v3-features.text
- tests/valid/draft-v3-features.v3.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/data/xml2rfc.css
- xml2rfc/writers/base.py
- xml2rfc/writers/html.py
- xml2rfc/writers/preptool.py
- xml2rfc/writers/text.py
Fixes #1100
With https://github.com/ietf-tools/xml2rfc/pull/1102/commits/205c09c84fb4f204d727ae64c56dab70d61fe768, `xml2rfc` tries to add the correct target for subseries when `referencegroup`'s `target` attribute is missing.
Updated examples:
| Format | Example |
| --- | --- |
| XML | [draft-foobar-00.xml](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.xml) |
| Text | [draft-foobar-00.txt](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.txt) |
| HTML | [draft-foobar-00.html](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.html) |
| PDF | [draft-foobar-00.pdf](https://t4.fq.nz/subseries-reference-targets/draft-foobar-00.pdf) |
> feat: Update subseries presentation

- .github/workflows/checks.yml
- tox.ini
- xml2rfc/walkpdf.py
This fixes the recursion issue in walkpdf introduced by PyPDF==4.1.0.
This fix is based @pubpub-zz's suggestion in https://github.com/py-pdf/pypdf/issues/2508#issuecomment-1986371461
Fixes #1111
> test: Fix recursion issue in walkpdf

- .github/workflows/checks.yml
- README.md
- docker/base.Dockerfile
- xml2rfc/run.py
- xml2rfc/walkpdf.py
* Use [xml2rfc-fonts](https://github.com/ietf-tools/xml2rfc-fonts) for tests.
* Bump up setup-python action to v5.
* Bump up checout action to v4.
* Restrict macOS testing to intel processor. _See #1129._
* Fix text extraction issues with updated fonts.
* Use xml2rfc-fonts in the docker image. Fixes #1121 
* Use xml2rfc-fonts [xml2rfc compatible version](https://github.com/ietf-tools/xml2rfc-fonts/releases/tag/3.22.0).
* Update documentation to use xml2rfc-fonts. Fixes #1030
> feat: Use fonts from xml2rfc-fonts

- .github/workflows/checks.yml
CodeQL Action v1 is deprecated.
See https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
> ci: Update CodeQL Action to v2

- requirements.txt
- setup.cfg
- xml2rfc/parser.py
- xml2rfc/run.py
- xml2rfc/util/unicode.py
- xml2rfc/utils.py
- xml2rfc/writers/html.py
- xml2rfc/writers/paginated_txt.py
- xml2rfc/writers/preptool.py
- xml2rfc/writers/text.py
* feat: Remove six. Fixes #1130 
* chore: Use context managers in `xml2rfc/parser.py`.
> feat: Remove dependency on six

- .github/workflows/checks.yml
- README.md
- docker/base.Dockerfile
- setup.cfg
- tox.ini
- xml2rfc/run.py
> feat: Pin WeasyPrint 61.2

- .github/workflows/checks.yml
- setup.cfg
- tox.ini
Weasyprint `61.2` requires `pydyf >= 0.8.0`.
Since `pydyf < 0.10.0` is best suited for us right now.
> build: Update pydyf version requirement

- Makefile
- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-miek-test.v3add-xinclude-w-revision.xml
- tests/valid/draft-miek-test.v3add-xinclude.xml
- tests/valid/draft-template.html
- tests/valid/draft-template.v2v3.xml
- tests/valid/draft-template.v3add-xinclude-w-revision.xml
- tests/valid/draft-template.v3add-xinclude.xml
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/rfc7911.v3add-xinclude-w-revision.xml
- tests/valid/rfc7911.v3add-xinclude.xml
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/v2v3.py
> fix(v2v3): Use bib.ietf.org for I-D xinclude references

- test.py
- tests/valid/draft-v3-features.text
- tests/valid/elements.bom.text
- tests/valid/elements.pages.text
- tests/valid/elements.text
- tests/valid/elements.wip.text
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/text.py
> fix(text): Capitalize "type" in non-ASCII artwork message

- .github/workflows/checks.yml
- test.py
Fixes #1178
This only enables `pytests` and skips PDF checks.
Getting the full test suite to work on Windows OS require lot more effort.
> ci: Enable tests on Windows OS

- xml2rfc/writers/pdf.py
Fixes #1160
Suggested by @liZe. [^1]
This fixes the line height issue documented wide.
Screenshots:
RFC 9421:
RFC 9591:
[^1]: https://github.com/Kozea/WeasyPrint/issues/2253#issuecomment-2353951920
> fix(pdf): Fix line height issue with superscripts

- test.py
- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-template.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/rfc7911.html
- tests/valid/rfc99999.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/__init__.py
- xml2rfc/run.py
- xml2rfc/writers/__init__.py
- xml2rfc/writers/base.py
- xml2rfc/writers/bib.py
With the new command line option `--use-bib`, xinclude with `datatracker.ietf.org` is replaced with `bib.ietf.org`.
Fixes #1167
> feat: Add option to update datatracker references

- tests/valid/docfile.html
- tests/valid/draft-miek-test.html
- tests/valid/draft-miek-test.v3.html
- tests/valid/draft-template.html
- tests/valid/draft-template.v3.html
- tests/valid/draft-v3-features.v3.html
- tests/valid/elements.v3.html
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/no-toc.v3.html
- tests/valid/rfc7911.html
- tests/valid/rfc7911.v3.html
- tests/valid/rfc9001.canonical.html
- tests/valid/rfc99999.html
- tests/valid/rfc99999.v3.html
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/writers/html.py
This removes path from the alternate link.
Fixes #1068
> fix(html): Use basename for alternative link

- xml2rfc/writers/preptool.py
> fix: Exit gracefully on artwork and sourcecode src file access errors

- tests/input/abbreviations.xml
- tests/valid/abbreviations.html
- tests/valid/abbreviations.nroff
- tests/valid/abbreviations.raw.txt
- tests/valid/abbreviations.txt
- tests/valid/indexes.pages.text
- tests/valid/indexes.prepped.xml
- tests/valid/indexes.text
- tests/valid/indexes.v3.html
- tests/valid/manpage.txt
- tests/valid/sourcecode.pages.text
- tests/valid/sourcecode.prepped.xml
- tests/valid/sourcecode.text
- tests/valid/sourcecode.v3.html
- xml2rfc/utils.py
Fixes #1205
* This adds `a.k.a.` to list of strings that doesn't mark end of a sentence.
* This improves not sentence end text-chunk identification by identifying abbreviated chunks in `(a.k.a. Foo` or `[i.e. Bar` as not sentence ending text chunks.
* Add `e.g.` to to list of strings that doesn't mark end of a sentence.
> fix(text): Improve sentence ending logic

- .github/workflows/pypi-publish.yml
This PR is following [Publishing package distribution releases using GitHub Actions CI/CD workflows](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages) guide.
This separates PyPI production publish and PyPI test publishing into two different jobs.
This also separates building to it's own job.
This also introduces distribution signing with Sigstore.
Fixes #1193
> build: Update Python publish GHA

- .github/workflows/checks.yml
- pyproject.toml
- tox.ini
- xml2rfc/writers/pdf.py
> chore(deps): Update WeasyPrint to v64.1

- xml2rfc/writers/html.py
This warning annoys a lot of people unnecessarily.
The argument that this means that the diagram doesn't stretch is true (it won't stretch), but misleading, because stretching is not a good goal to seek.  Diagrams in RFCs often have text, which either becomes too large or too small when stretched.  Consequently, the right choice is to set width and height in many cases.
Indeed, the example in RFC 7992 includes width and height (and no viewbox, but that's a separate issue).  RFC 7996 does nothing about this.  This warning is therefore overreach.
> feat: Remove warning about SVG width and height

- ACKNOWLEDGMENTS.md
- pyproject.toml
The list of names were compiled by using:
* `git shortlog -sne` command (e6a55c57b1272bfa5b72bbf5e2eb87a7259b280d)
* authors from GitHub issues (7292a0bab3c7e7a9cc4a92b4da9d4e574c4ba60a)
This PR also removes `maintainers` entry from the `pyproject.toml` and replaces `IETF Tools` as the author.
> chore: Add ACKNOWLEDGMENTS.md file

- .github/workflows/checks.yml
- pyproject.toml
This PR updates `xml2rfc` `pdf` extra requirement to v65.0[^1].
Fixes #1226 
[^1]: https://github.com/Kozea/WeasyPrint/releases/tag/v65.0
> chore(pdf): Update WeasyPrint to v65.0

- .github/workflows/pypi-publish.yml
Fixes GitHub publishing issues[^1].
[^1]: https://github.com/ietf-tools/xml2rfc/actions/runs/13602887325/job/38030952801
> ci: Fix GitHub publish issue

- test.py
- xml2rfc/writers/base.py
`get_relevant_pis` searches from local to global, but then uses the most global PI, so a local override doesn't work.
> fix: Local PIs need to override global ones, not the other way around

- xml2rfc/util/name.py
This PR updates the logic that generates short author names such that when initials are not provided, and the name being initialed is only one character long, there is no period appended after the character. 
This addresses the problem raised in #1204 regarding the handling of my name. The output format for RFC-to-be 9799 is now:
```text
Internet Engineering Task Force (IETF)                     Q Misell, Ed.
Request for Comments: 9799                                      AS207960
Category: Standards Track                                      June 2025
ISSN: 2070-1721
```
> Fix for #1204 - single letter names 

- xml2rfc/writers/pdf.py
This is an attempt to address #1245
> fix(pdf): For monospaced text, Add Noto Sans Mono before NOTO_SYMBOLS

- pyproject.toml
Hi,
Since this previous PR https://github.com/ietf-tools/xml2rfc/pull/1079, setuptools is not needed at runtime anymore.
Greetings
> setuptools is not needed at runtime anymore
