.devcontainer/devcontainer.json, .gitignore, .vscode/launch.json, .vscode/tasks.json
Adds preconfigured debug configuration for VS Code + extra recommended extensions
=> chore: add vscode dev debug configs

tests/input/indexes.xml, tests/valid/docfile.py36.html, tests/valid/docfile.py37.html, tests/valid/docfile.py38.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.py36.html, tests/valid/indexes.v3.py37.html, tests/valid/indexes.v3.py38.html, tests/valid/manpage.txt, xml2rfc/writers/preptool.py
=> fix: Make index sort case insensitive

Makefile, tests/input/sourcecode.xml, tests/valid/docfile.py36.html, tests/valid/docfile.py37.html, tests/valid/docfile.py38.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.py36.html, tests/valid/indexes.v3.py37.html, tests/valid/indexes.v3.py38.html, tests/valid/manpage.txt, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.py36.html, tests/valid/sourcecode.v3.py37.html, tests/valid/sourcecode.v3.py38.html, xml2rfc/data/xml2rfc.css, xml2rfc/writers/html.py
=> fix: Make long sourcecode sections breakable

Makefile, tests/input/no-toc.xml, tests/valid/docfile.py36.html, tests/valid/docfile.py37.html, tests/valid/docfile.py38.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.py36.html, tests/valid/indexes.v3.py37.html, tests/valid/indexes.v3.py38.html, tests/valid/manpage.txt, tests/valid/no-toc.pages.text, tests/valid/no-toc.prepped.xml, tests/valid/no-toc.text, tests/valid/no-toc.v3.py36.html, tests/valid/no-toc.v3.py37.html, tests/valid/no-toc.v3.py38.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.py36.html, tests/valid/sourcecode.v3.py37.html, tests/valid/sourcecode.v3.py38.html, xml2rfc/writers/text.py
=> fix: Render text without toc

.github/workflows/checks.yml, setup.py, tox.ini, xml2rfc/writers/doc.py
This PR consists of cherry picked changes from #727 because the original PR is stale and complicated to update via GitHub.
=> build: Add support for Python 3.10

xml2rfc/writers/preptool.py
(There may be a better solution, but this fixes the crash for now.)
=> fix: Handle date type errors gracefully

.github/workflows/checks.yml, Dockerfile, setup.py, tox.ini
=> feat!: Drop support for Python 3.6

requirements.txt, tests/valid/docfile.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html
* chore(deps): Update markupsafe requirement to >=2.1.1
* chore(deps): Update pycountry requirement to >=22.3.5
* chore(deps): Update lxml requirement to >=4.9.0
* chore(deps): Remove intervaltree 3.0.0 version restriction
* chore(deps): Remove jinja2 3.0.0 version restriction
=> chore(deps): Update Python dependencies

tests/valid/draft-miek-test.v2v3.xml, tests/valid/draft-miek-test.v3add-xinclude.xml, tests/valid/draft-template.v2v3.xml, tests/valid/draft-template.v3add-xinclude.xml, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc6787.v2v3.xml, tests/valid/rfc6787.v3add-xinclude.xml, tests/valid/rfc7911.v2v3.xml, tests/valid/rfc7911.v3add-xinclude.xml, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/parser.py, xml2rfc/writers/v2v3.py
=> fix: Use bib.ietf.org for citations

test.py, tests/input/elements.xml, tests/valid/elements.bom.text, tests/valid/elements.pages.text, tests/valid/elements.prepped.xml, tests/valid/elements.text, tests/valid/elements.v3.html, tests/valid/elements.wip.text, xml2rfc/util/unicode.py, xml2rfc/writers/base.py, xml2rfc/writers/preptool.py, xml2rfc/writers/v2v3.py
=>  fix: Render unicode characters in SVG elements correctly 

README.md
* Updated instructions to install WeasyPrint.
* Add getting started information for contributors.
=> docs: Update README file [skip ci]

.github/workflows/checks.yml, requirements.txt, tox.ini
=> build: Move out pyflakes from requirements.txt

tests/valid/docfile.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/writers/preptool.py
=>  fix: Prevent submission date warnings for RFCs 

xml2rfc/run.py, xml2rfc/writers/base.py, xml2rfc/writers/html.py
This is what I was talking about on the issue.  Fairly unobtrusive.
Closes #470.
=> Add an option to disable rfc-local.css link

tests/valid/docfile.html, tests/valid/manpage.txt
Valid tests updates for #840 
I couldn't update the original PR, hence new PR.
=> test: Update valid tests for --no-rfc-local option

xml2rfc/data/xml2rfc.css
Fix for #834.
#834 will be kept open to evaluate the use of flexbox.
=> fix: Artwork align center correctly

tests/input/elements.xml, tests/valid/elements.bom.text, tests/valid/elements.pages.text, tests/valid/elements.prepped.xml, tests/valid/elements.text, tests/valid/elements.v3.html, tests/valid/elements.wip.text, xml2rfc/util/name.py
=>  fix: Return orgnization for orgnization only contacts 

test.py, tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/draft-template.v3.html, tests/valid/draft-v3-features.v3.html, tests/valid/elements.v3.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/writers/html.py
=> fix: Use spcified font families on SVG

tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/rfc7911.html, xml2rfc/data/xml2rfc.css
=> fix: Add bottom margin to .artwork > pre

requirements.txt, xml2rfc/writers/text.py
Kitchen is unmainted and should no longer be used, hence we this drops the dependency on kitchen.
=> Drop dependency on kitchen

tests/input/elements.txt, tests/input/elements.xml, tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/elements.pages.text, tests/valid/elements.prepped.xml, tests/valid/elements.text, tests/valid/elements.v3.html, tests/valid/elements.wip.text, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/writers/text.py
Fixes table colspan issues in text output. See #833.
=>  fix: Expand table columns in text output 

tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/data/xml2rfc.css
=>  fix: Fix margin issue with dl after p inside a li 

.github/workflows/checks.yml, configtest.py, docker/dev.Dockerfile, setup.py, tox.ini, xml2rfc/walkpdf.py
Move from PyPDF2 to pypdf>=3.2.1
Reference: https://github.com/ietf-tools/xml2rfc/issues/933#issuecomment-1368069230
=> chore(deps): Move from PyPDF2 to pypdf>=3.2.1

test.py, tests/valid/docfile.html, tests/valid/manpage.txt, xml2rfc/boilerplate_rfc_7841.py, xml2rfc/data/reference.rnc, xml2rfc/data/reference.rng, xml2rfc/data/referencegroup.rng, xml2rfc/data/v3.rnc, xml2rfc/data/v3.rng, xml2rfc/strings.py, xml2rfc/writers/preptool.py
Add editorial stream as per #896 and [Section 6.3 of RFC 9280](https://www.rfc-editor.org/rfc/rfc9280.html#section-6.3).
Fixes #896
=> feat: Add editorial stream

requirements.txt, tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-miek-test.v3add-xinclude.xml, tests/valid/draft-template-old.exp.xml, tests/valid/draft-template.exp.xml, tests/valid/draft-template.html, tests/valid/draft-template.pages.text, tests/valid/draft-template.prepped.xml, tests/valid/draft-template.text, tests/valid/draft-template.txt, tests/valid/draft-template.v3add-xinclude.xml, tests/valid/draft-v3-features.prepped.xml, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.exp.xml, tests/valid/rfc7911.html, tests/valid/rfc7911.v3add-xinclude.xml, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/util/postal.py
=> fix: Update for google-i18n-address 3.0.0

tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template-old.exp.xml, tests/valid/draft-template-old.prepped.xml, tests/valid/draft-template-old.v2v3.xml, tests/valid/draft-template.exp.xml, tests/valid/draft-template.html, tests/valid/draft-template.prepped.xml, tests/valid/draft-v3-features.prepped.xml, tests/valid/elements.prepped.xml, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.exp.xml, tests/valid/rfc7911.html, tests/valid/rfc7911.prepped.xml, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/writers/text.py
This PR fixes an edge case text pagination.
=> fix: Improve pagination in text output

tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/data/xml2rfc.css
=> fix: Make block quotes symmetric

.github/workflows/checks.yml, docker/dev.Dockerfile, setup.cfg, tox.ini
=> feat: Drop support for Python 3.7

.github/workflows/checks.yml, docker/dev.Dockerfile, setup.cfg, tox.ini
=> feat: Add support for Python 3.12

.github/workflows/pypi-publish.yml
Allow chore commits to bump patch version
=> ci: Update pypi-publish.yml

xml2rfc/utils.py, xml2rfc/writers/base.py
=> fix: Use raw string notation for regex

tests/input/draft-v3-features.xml, tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/draft-v3-features.prepped.xml, tests/valid/draft-v3-features.text, tests/valid/draft-v3-features.v3.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/writers/html.py, xml2rfc/writers/text.py
Revert changes from #1089 (#1067).
Fixes #1097
=> revert: #1089 (Treat referencegroup entries similarly to reference entries)

xml2rfc/writers/preptool.py
=> fix: Change non-current year error to a warning

tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/data/xml2rfc.css
=> fix: Avoid breaking citation labels

test.py, xml2rfc/writers/base.py
* refactor: Remove an obsolete warning
* refactor: Remove redundant import
* feat: Validate docName and seriesInfo value for I-D
Fixes #1115
=> feat: Validate docName and seriesInfo value for I-D

tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/data/xml2rfc.css
=> fix: Use correct list style for upper case roman

tests/input/elements.xml, tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/draft-v3-features.text, tests/valid/elements.bom.text, tests/valid/elements.pages.text, tests/valid/elements.prepped.xml, tests/valid/elements.text, tests/valid/elements.v3.html, tests/valid/elements.wip.text, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/writers/text.py
=> fix(text): Render ol and ul inside blockquote correctly

xml2rfc/data/xml2rfc.css
=> fix: Add background to tt and code inside dt

.github/workflows/checks.yml, docker/dev.Dockerfile, setup.cfg, tox.ini
=> feat: Add support for Python 3.13

xml2rfc/writers/legacy_html.py
=> fix: Remove deprecated cgi method

.github/workflows/checks.yml, docker/dev.Dockerfile, setup.cfg, tox.ini
=> feat: Drop support for Python 3.8

README.md, xml2rfc/run.py
=> fix: Add quotes to pip extra command

xml2rfc/data/xml2rfc.css
Fixes #702 
Also addresses #606 
* [RFC 9622](https://t4.fq.nz/xml2rfc-1207/rfc9622.pdf)
* [RFC 9127](https://t4.fq.nz/xml2rfc-1207/rfc9127.pdf)
* [RFC 8996](https://t4.fq.nz/xml2rfc-1207/rfc8996.pdf)
* [RFC 9720](https://t4.fq.nz/xml2rfc-1207/rfc9720.pdf)
=> fix(pdf): Fix suboptimal overflow issues in the header

docker/base.Dockerfile, docker/dev.Dockerfile
=> build: Fix and improve Docker images

xml2rfc/writers/base.py
=> fix: Make warnings respect quite flag

tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/rfc99999.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/data/xml2rfc.css, xml2rfc/run.py, xml2rfc/writers/base.py, xml2rfc/writers/html.py, xml2rfc/writers/pdf.py
=>  fix(pdf): Scale large SVG artwork

.github/workflows/pypi-publish.yml
=> ci: Fix release GHA issues

.github/workflows/pypi-publish.yml
=> build: Create PR with CHANGELOG and version update

tests/valid/docfile.html, tests/valid/draft-miek-test.html, tests/valid/draft-template.html, tests/valid/indexes.pages.text, tests/valid/indexes.prepped.xml, tests/valid/indexes.text, tests/valid/indexes.v3.html, tests/valid/manpage.txt, tests/valid/rfc7911.html, tests/valid/rfc99999.html, tests/valid/sourcecode.pages.text, tests/valid/sourcecode.prepped.xml, tests/valid/sourcecode.text, tests/valid/sourcecode.v3.html, xml2rfc/data/xml2rfc.css
Fixes #1281 
This PR updates CSS to use self hosted fonts.
=> feat(html): Use self hosted fonts
